# -*- coding: utf-8 -*-
"""Loads every icon module and writes icons32.js.

An icon is a file under `icons/`, not a block in here and a row in a table over
there. This loads them all, orders them the way the game's own talent trees are
ordered, and writes the JS the preview and the artboards read.

    python draw-icons.py

The JS it writes is generated: hand-tweak a pixel there and the next run
overwrites it, so bring the tweak back into the icon's module.
"""
import glob
import importlib.util
import io
import os
import re
import sys

import iconkit

HERE = os.path.dirname(os.path.abspath(__file__))
TREES = os.path.join(HERE, '..', '..', 'src', 'sim', 'talents.ts')


def load_modules():
    """Imports every icons/*.py, which is what registers them."""
    for path in sorted(glob.glob(os.path.join(HERE, 'icons', '*.py'))):
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem.startswith('_'):
            continue
        before = {i['id'] for i in iconkit.ICONS}
        spec = importlib.util.spec_from_file_location('icon_%s' % stem, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        added = {i['id'] for i in iconkit.ICONS} - before
        # A file that registers nothing is an icon nobody will notice is
        # missing, and one that registers a different name than it is called is
        # a file nobody will find again.
        assert added == {stem}, (
            'icons/%s.py registered %s, expected exactly {%r}'
            % (stem, sorted(added) or 'nothing', stem))


def talent_order():
    """Every talent id in tree order, from the game's own table.

    One home for the order: the icon sheet then reads hero by hero and tier by
    tier without a second list here that has to be kept level with that one.
    """
    src = io.open(TREES, encoding='utf-8').read()
    heroes = ['archer', 'wizard', 'knight', 'ranger', 'sapper']
    at = {h: src.index('\n  %s: {' % h) for h in heroes}
    order, seen = [], {}
    for h in sorted(heroes, key=lambda k: at[k]):
        later = [at[k] for k in heroes if at[k] > at[h]]
        body = src[at[h]:min(later) if later else src.index('\n};', at[h])]
        for m in re.finditer(r"id: '(\w+)'", body):
            seen[m.group(1)] = h.upper()
            order.append(m.group(1))
    return order, seen


def main():
    load_modules()
    order, hero_of = talent_order()
    have = {i['id']: i for i in iconkit.ICONS}

    # Both directions, the way the repo checks every other table pair: an icon
    # for a talent that does not exist is a drawing nobody can reach, and the
    # count of what is still to draw is worth printing rather than guessing.
    stray = sorted(set(have) - set(order))
    assert not stray, 'icons for talents that do not exist: %s' % stray
    for icon_id, icon in have.items():
        want = hero_of[icon_id]
        assert icon['hero'] == want, (
            '%s says hero=%r; talents.ts has it under %s'
            % (icon_id, icon['hero'], want))

    icons = [have[i] for i in order if i in have]
    todo = [i for i in order if i not in have]

    parts = [HEADER % ',\n'.join(
        "  %s: { %s }" % (name, ', '.join("%s: '%s'" % (c, h) for c, h in ramp.items()))
        for name, ramp in iconkit.RAMPS.items())]
    for icon in icons:
        parts.append("  {\n")
        parts.append("    id: '%s', name: '%s', hero: '%s', kind: '%s', cat: '%s',\n"
                     % (icon['id'], icon['label'], icon['hero'], icon['kind'], icon['cat']))
        parts.append("    why: '%s',\n" % icon['why'])
        parts.append("    legend: mk(%s),\n"
                     % ', '.join("'%s'" % r for r in icon['ramps']))
        parts.append("    rows: [\n")
        for row in icon['rows']:
            parts.append("      '%s',\n" % row)
        parts.append("    ],\n  },\n")
    parts.append(TAIL)

    io.open(os.path.join(HERE, 'icons32.js'), 'w', encoding='utf-8',
            newline='').write(''.join(parts))
    print('wrote icons32.js (%d of %d talents drawn)' % (len(icons), len(order)))
    if todo:
        print('still to draw (%d): %s' % (len(todo), ', '.join(todo)))


HEADER = '''/**
 * Talent icons as 32x32 pixel art in the Heroes-of-Might-and-Magic idiom: one
 * painted object seated in a brass bezel, keyed from the upper left.
 *
 * GENERATED by draw-icons.py from the modules in `icons/`. Edit there.
 *
 * WHY NOT 16x16. That pass read as a diagram and the owner called it right.
 * Three values cannot model a form, an unframed shape has nothing to be lit
 * against, and flat vertical bands of colour are not shading. Every surface
 * here runs the same six steps -- dark edge, specular, highlight, midtone,
 * core shadow, and one pixel of reflected light on the far edge, which is the
 * step that makes a shape read as round rather than as a stripe.
 *
 * The bezel, the ground, the cast shadow and the travelling sheen are
 * generated in `compose.mjs`, so an icon here is only its object. Grids are 32
 * rows of exactly 32 characters; `.` shows the socket through, and everything
 * is clipped to the socket, so an object that runs off the edge reads as
 * cropped.
 *
 * Order is the game's own tree order, read out of src/sim/talents.ts.
 */

/** Icon ramps, richer than the sprite ramps: these are read on dark brass. */
export const RAMPS = {
%s,
};

const mk = (...names) => Object.assign({}, ...names.map((n) => RAMPS[n]));

export const ICONS = [
'''

TAIL = '''];

for (const i of ICONS) {
  if (i.rows.length !== 32) throw new Error(`${i.id}: ${i.rows.length} rows`);
  const bad = i.rows.findIndex((r) => r.length !== 32);
  if (bad >= 0) throw new Error(`${i.id}: row ${bad} is ${i.rows[bad].length} wide`);
  // A character with no legend entry paints NOTHING -- compose.mjs reads
  // `legend[ch] ?? null` and moves on. That is how a leather shield face drawn
  // against a steel legend rendered as a blank plate with no error anywhere.
  const used = new Set(i.rows.join('').split('').filter((c) => c !== '.'));
  const missing = [...used].filter((c) => !(c in i.legend)).sort();
  if (missing.length) {
    throw new Error(`${i.id} uses ${missing.join('')} with no ramp for it`);
  }
}
'''

if __name__ == '__main__':
    main()
