# -*- coding: utf-8 -*-
"""Loads every ultimate icon module and writes ultimates48.js.

    python draw-ultimates.py

A sibling of draw-icons.py rather than a flag on it. The two sets differ in
every way that matters -- 48 px against 32, a gold frame against brass, one
shared socket against five category ones, and an order that comes from a
hand-written manifest rather than from the game's own table -- so folding them
together would mean a `kind` flag threaded through both, which is two
functions wearing one name.

What they DO share is iconkit: the ramps, the grid, the registry, and every
check that refuses a mistake which would otherwise fail silently.
"""
import glob
import importlib.util
import io
import os
import sys

import iconkit
from ultimates import BY_ID, ORDER, ULTIMATES

HERE = os.path.dirname(os.path.abspath(__file__))


def load_modules():
    """Imports every ultimates/*.py, which is what registers them."""
    for path in sorted(glob.glob(os.path.join(HERE, 'ultimates', '*.py'))):
        stem = os.path.splitext(os.path.basename(path))[0]
        if stem.startswith('_'):
            continue
        before = {i['id'] for i in iconkit.ICONS}
        spec = importlib.util.spec_from_file_location('ult_%s' % stem, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        added = {i['id'] for i in iconkit.ICONS} - before
        # A file that registers nothing is an icon nobody will notice is
        # missing; one that registers another name is a file nobody finds again.
        assert added == {stem}, (
            'ultimates/%s.py registered %s, expected exactly {%r}'
            % (stem, sorted(added) or 'nothing', stem))


def check_manifest():
    """Every hero has exactly one of each slot, and no id is used twice."""
    assert len(ORDER) == len(set(ORDER)), 'duplicate id in ultimates.py'
    slots = {}
    for icon_id, _label, hero, slot, _why in ULTIMATES:
        assert slot in ('first', 'second'), '%s: bad slot %r' % (icon_id, slot)
        assert (hero, slot) not in slots, (
            '%s and %s are both the %s ultimate for the %s'
            % (slots[(hero, slot)], icon_id, slot, hero))
        slots[(hero, slot)] = icon_id
    for hero in {h for _i, _l, h, _s, _w in ULTIMATES}:
        for slot in ('first', 'second'):
            assert (hero, slot) in slots, 'the %s has no %s ultimate' % (hero, slot)


def main():
    check_manifest()
    load_modules()
    have = {i['id']: i for i in iconkit.ICONS}

    # Both directions, the way draw-icons.py checks talents: an icon for an
    # ultimate that is not in the manifest is a drawing nobody can reach, and
    # the count still to draw is worth printing rather than guessing at.
    stray = sorted(set(have) - set(ORDER))
    assert not stray, 'icons for ultimates that do not exist: %s' % stray
    for icon_id, icon in have.items():
        want = BY_ID[icon_id][2]
        assert icon['hero'] == want, (
            '%s says hero=%r; the manifest has it under %s'
            % (icon_id, icon['hero'], want))
        assert icon['cat'] == 'ultimate', (
            '%s: an ultimate sits on the ultimate ground, not %r'
            % (icon_id, icon['cat']))
        assert icon['size'] == iconkit.ULT_N, (
            '%s is %d px; ultimates draw at %d'
            % (icon_id, icon['size'], iconkit.ULT_N))

    icons = [have[i] for i in ORDER if i in have]
    todo = [i for i in ORDER if i not in have]

    ramps = ','.join(
        '\n  %s: { %s }' % (name, ', '.join("%s: '%s'" % (c, h) for c, h in ramp.items()))
        for name, ramp in iconkit.RAMPS.items())
    parts = [HEADER % ramps]
    for icon in icons:
        slot = BY_ID[icon['id']][3]
        parts.append('  {\n')
        parts.append(
            "    id: '%s', name: '%s', hero: '%s', slot: '%s', kind: '%s', cat: '%s',\n"
            % (icon['id'], icon['label'], icon['hero'], slot, icon['kind'], icon['cat']))
        parts.append('    size: %d,\n' % icon['size'])
        parts.append("    why: '%s',\n" % icon['why'])
        parts.append("    legend: mk(%s),\n"
                     % ', '.join("'%s'" % r for r in icon['ramps']))
        parts.append('    rows: [\n')
        for row in icon['rows']:
            parts.append("      '%s',\n" % row)
        parts.append('    ],\n  },\n')
    parts.append(TAIL % (iconkit.ULT_N, iconkit.ULT_N))

    io.open(os.path.join(HERE, 'ultimates48.js'), 'w', encoding='utf-8',
            newline='').write(''.join(parts))
    print('wrote ultimates48.js (%d of %d ultimates drawn)' % (len(icons), len(ORDER)))
    if todo:
        print('still to draw (%d): %s' % (len(todo), ', '.join(todo)))


HEADER = '''/**
 * Ultimate icons as 48x48 pixel art: the talent sigils' idiom one rank up --
 * one painted object seated in a GOLD bezel on the shared ultimate ground,
 * rather than brass on a category colour.
 *
 * GENERATED by draw-ultimates.py from the modules in `ultimates/`. Edit there.
 *
 * WHY 48 AND NOT 32. A talent is one of forty in a row; an ultimate is one of
 * two on a card, and it is the only choice of its kind a character makes. Half
 * again the resolution is what buys detail that reads at card size. The forty
 * talent icons are untouched by it: the size rides on the icon rather than on
 * a constant both sets share, and all forty were proven to composite
 * identically through the change.
 *
 * The two for a hero are drawn deliberately UNLIKE each other. The fork is the
 * message, and art that rhymed would soften it.
 */

/** Shared with the talent icons: one home for the ramps. */
export const RAMPS = {%s,
};

const mk = (...names) => Object.assign({}, ...names.map((n) => RAMPS[n]));

export const ULTIMATES = [
'''

TAIL = '''];

for (const i of ULTIMATES) {
  if (i.rows.length !== %d) throw new Error(`${i.id}: ${i.rows.length} rows`);
  const bad = i.rows.findIndex((r) => r.length !== %d);
  if (bad >= 0) throw new Error(`${i.id}: row ${bad} is ${i.rows[bad].length} wide`);
  // A character with no legend entry paints NOTHING -- compose.mjs reads
  // `legend[ch] ?? null` and moves on, so a face drawn in the wrong ramp comes
  // out as a blank plate with no error anywhere. That cost an afternoon once.
  const used = new Set(i.rows.join('').split('').filter((c) => c !== '.'));
  const missing = [...used].filter((c) => !(c in i.legend)).sort();
  if (missing.length) {
    throw new Error(`${i.id} uses ${missing.join('')} with no ramp for it`);
  }
}
'''

if __name__ == '__main__':
    main()
